### ISSUE TITLE
[Feature Request] "Post Window" output channel

### ISSUE THREAD

**Issue by okhick** [scztt/vscode-supercollider#14]
What are your thoughts on adding another `OutputChannel` just for `results`? The idea being it would function like the Post window in SCIDE. I know we have the `showInformationMessage` toasts, but those can be a little distracting that I don't find them very useful for debugging or rapid logging. We can keep the current channel for extension/LSP debugging.

I'm happy to put up a PR for this as long as it's something you're willing to consider!

**Comment by scztt** [comment]
The current `supercollider` Output is just the stdout of the sclang process - if we showed the results here, it would be exactly the same content as the current Post window in ScIDE. I think we just need to `postln` the results in `EvaluateProvider.sc`. I'm definitely in favor of this.

**Comment by okhick** [comment]
Yes that definitely does work! However there's still the noise from the language server that I'm trying to quiet. It's fine for debugging, but for the average supercollider user it will probably just get in the way. Does that make sense?

**Comment by scztt** [comment]
This should be much better now with the default configuration. Please try updating `vscode-supercollider`, `LanguageServer.quark`, and `Deferred.quark` (there's a bug fix in the latter one). 

The current behavior:
1. LanguageServer.quark logging is turned OFF by default, so you won't get spammed. I also fixed some
2. Results are posted following the normal behavior, based on `supercollider.sclang.postEvaluateResults` and `supercollider.sclang.evaluateResultPrefix` settings.
3. Log level is now connected to the `supercollider.languageServerLogLevel` setting.

The vscode settings are only applied on launch, and are not sent to the server if you change them - I'll fix this later, but it will take a little tinkering.

**Comment by okhick** [comment]
Hey nice! This is really starting to feel like Supercollider in VSCode! I think the LanguageServer.quark submodule is linked a commit behind--I had to manually pull down develop to get everything to work.

Also is there a place I should be updating `Deferred.quark` from? It looks like I have the latest version (v0.0.2) and I see it's throwing an error.

**Comment by scztt** [comment]
> Hey nice! This is really starting to feel like Supercollider in VSCode! I think the LanguageServer.quark submodule is linked a commit behind--I had to manually pull down develop to get everything to work.

Pushed, this should be up to date now.

> Also is there a place I should be updating Deferred.quark from? It looks like I have the latest version (v0.0.2) and I see it's throwing an error.

SC Quarks don't REALLY handle versions / commit dependencies correctly. You should be able to run `Quark("https://github.com/scztt/Deferred.quark").update` to update to the newest version.

**Comment by scztt** [comment]
Closing this for now, but please re-open if there's anything else on this topic that should be addressed.
