### ISSUE TITLE
instruction #5 of the readme is a bit criptic

### ISSUE THREAD

**Issue by tremblap** [scztt/vscode-supercollider#19]
Hello

Thanks for your work on this. I try to get it to work and in my (MacOS) SCIDE I cannot find the `LanguageServer.quark` and certainly not through what is written at #5 :)

Any precision for first time users welcome.

**Comment by scztt** [comment]
I updated the readme a little, and provided some documentation on the "Document" class issue, does this help?

https://github.com/scztt/vscode-supercollider/blob/develop/README.md

**Comment by tremblap** [comment]
It does a little. Now I have 2 json, and in the SCIDE one is as it was (no quarks and happy :). but I wonder if I need all of these in the VSCode one - this is the readout of the 'output' pane when it loads now:

> compiling class library...
	Found 855 primitives.
	Compiling directory '/Applications/SuperCollider.app/Contents/Resources/SCClassLibrary'
	Compiling directory '/Users/pa/Library/Application Support/SuperCollider/Extensions'
	Compiling directory '/Users/pa/Library/Application Support/SuperCollider/downloaded-quarks/Singleton'
	Compiling directory '/Users/pa/Library/Application Support/SuperCollider/downloaded-quarks/Collapse'
	Compiling directory '/Users/pa/Library/Application Support/SuperCollider/downloaded-quarks/WindowViewRecall'
	Compiling directory '/Users/pa/Library/Application Support/SuperCollider/downloaded-quarks/Log'
	Compiling directory '/Users/pa/Library/Application Support/SuperCollider/downloaded-quarks/Deferred'
	Compiling directory '/Users/pa/Library/Application Support/SuperCollider/downloaded-quarks/LanguageServer'
	numentries = 1018939 / 16947910 = 0.06
	6145 method selectors, 2758 classes
	method table size 16945896 bytes, big table size 135583280
	Number of Symbols 14937
	Byte Code Size 519315
	compiled 510 files in 0.69 seconds
compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 2.85 seconds
ERROR: Message 'addRawRecvFunc' not understood.
Perhaps you misspelled 'addOSCRecvFunc', or meant to call 'addRawRecvFunc' on another receiver?
RECEIVER:
Instance of Main {    (0x7fa2180e8058, gc=CC, fmt=00, flg=00, set=04)
  instance variables [11]
    classVars : instance of Array (0x7fa200030b40, size=594, set=10)
    interpreter : instance of Interpreter (0x7fa2180e8428, size=30, set=5)
    curThread : instance of Thread (0x7fa2180e8188, size=28, set=5)
    mainThread : instance of Thread (0x7fa2180e8188, size=28, set=5)
    schedulerQueue : instance of Array (0x7fa23802bf40, size=1, set=12)
    nowExecutingPath : nil
    platform : instance of OSXPlatform (0x7fa2180e8868, size=9, set=4)
    argv : nil
    recvOSCfunc : nil
    prRecvOSCFunc : nil
    openPorts : instance of Set (0x7fa2199f48f8, size=2, set=2)
}
ARGS:
Instance of Function {    (0x7fa219a0e208, gc=C8, fmt=00, flg=00, set=02)
  instance variables [2]
    def : instance of FunctionDef in Method LSPConnection:start
    context : Frame (0x7fa20159cb08) of LSPConnection:start
}
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = <instance of Main>
		arg selector = 'addRawRecvFunc'
		arg args = [*1]
	LSPConnection:start
		arg this = <instance of LSPConnection>
	< FunctionDef in Method Meta_LSPConnection:initClass >  (no arguments or variables)
	Function:doOnStartUp
		arg this = <instance of Function>
	ArrayedCollection:do
		arg this = [*8]
		arg function = <instance of Function>
		var i = 5
	List:do
		arg this = <instance of List>
		arg function = <instance of Function>
	Meta_StartUp:run
		arg this = <instance of Meta_StartUp>
	Main:startup
		arg this = <instance of Main>
		var didWarnOverwrite = false
^^ ERROR: Message 'addRawRecvFunc' not understood.
Perhaps you misspelled 'addOSCRecvFunc', or meant to call 'addRawRecvFunc' on another receiver?
RECEIVER: a Main
