### ISSUE TITLE
Unable to open refactor-com-port branch of Supercollider

### ISSUE THREAD

**Issue by dmorgan-github** [scztt/vscode-supercollider#2]
macOs : Monterey
chip: M1 Pro
build: https://github.com/supercollider/supercollider/actions/runs/2008993369

[SuperCollider-4560cacc078d9c17f6947ca7a13d6e9630149ca5-macOS.dmg](https://github.com/supercollider/supercollider/suites/5722671362/artifacts/189175028)

I get the following error:
```
Interpreter has crashed or stopped forcefully. [Exit code: 11]
```

**Comment by scztt** [comment]
That's for the report. Can you post a crash log? These should be in `~/Library/Logs/DiagnosticReports`, look for scsynth.

**Comment by dmorgan-github** [comment]
i see one for sclang

[sclang-2022-03-21-201149.txt](https://github.com/scztt/vscode-supercollider/files/8320723/sclang-2022-03-21-201149.txt)

**Comment by scztt** [comment]
Closing, this should be fixed in the branch (we can re-open if we find other repro cases for this).
