### ISSUE TITLE
Independent help document theme from SC-IDE?

### ISSUE THREAD

**Issue by prko** [scztt/vscode-supercollider#21]
Thanks for your great job!

I am still using SC-IDE and your SuperCollider extension for VS Code together.

Is there a way to use two styles of Help document independently for your "SuperCollider extension for VS Code" and "SC-IDE"?

Currently, I have added the following code block to custom.css and I can read the help documents in SC-IDE without any problem, but the readability in vscdoe is slightly worse.
So I think it would be good if the SuperCollider extension for VS Code would use a different file than custom.css, because the help document colour in SC-IDE and your vscode extension are not the same.

```
@media screen {
    body {
        background: #232430/*#1f1f20*/;
        color: #232430/*#1f1f20*/;
        -webkit-filter: invert(90%);
        filter: invert(90%) ;
    }
    
    body::-webkit-scrollbar {
      width: 12px;               /* width of the entire scrollbar */
    }
    
    body::-webkit-scrollbar-track {
      background: #333;        /* color of the tracking area */
    }
    
    body::-webkit-scrollbar-thumb {
      background-color: #666;    /* color of the scroll thumb */
      border-radius: 20px;       /* roundness of the scroll thumb */
      border: 3px solid #333;  /* creates padding around scroll thumb */
    }
}
```

**Comment by scztt** [comment]
This is an issue that has to be resolved in SuperCollider itself - right now, `custom.css` is applied last, after ide specific style in frontend.css, so it will always override ide-specific changes:
```
    <link rel='stylesheet' href='../frontend.css' type='text/css' />
    <link rel='stylesheet' href='../custom.css' type='text/css' />
```

I'm not really sure what a good solution to this problem is, unfortunately

**Comment by prko** [comment]
I understand the difficulty! Thank you for your efforts in resolving so many requests!
