### ISSUE TITLE
[request] folding code lines

### ISSUE THREAD

**Issue by prko** [scztt/vscode-supercollider#28]
Dear scztt,

Currently, the folding code feature in the scd file is only applied when a pair of parentheses "(" and ")" appears as the first character of the lines, as follows:
<img width="677" alt="Screenshot 2023-11-03 at 12 19 50" src="https://github.com/scztt/vscode-supercollider/assets/416281/9e3b4afe-027e-4ec7-aafe-39b1c0f51703">

Could it be extended to any of the following?
- Parenthesis pairs ("(" and ")") across lines
- Bracket pairs("[" and "]") across lines
- Brace pairs("{" and "}") across lines

Thank you for your time and effort!

**Comment by scztt** [comment]
I added an enhancement to the backlog for this: https://github.com/scztt/sclang-format/issues/1

**Comment by prko** [comment]
Thank you very much!
