### ISSUE TITLE
Indentation behavior upon <return> after vertical-bar arg list: extra tab

### ISSUE THREAD

**Issue by jamshark70** [scztt/vscode-supercollider#29]
The following sequence results in dodgy indentation:

```
// type 'p.collect {' -- closing brace is auto-inserted, OK
p.collect {}

// type '<space> |' -- closing | is auto-inserted, OK
p.collect { ||}

// fill in arg, right-arrow, and then "return" after arg list
p.collect { |path|
    }
```

The closing brace now has an extra indent level.

The same does not occur when using an `arg` list.

**Comment by scztt** [comment]
Are you using [the sclang formatter](https://github.com/scztt/sclang-format) or is this just vscode indenting? 

I think by the rules of the sclang formatter, this is the correct indentation. IIRC the rule that made the most sense was that for statements spread over two lines, the second line would ALWAYS be indented. Without this, there is no visual cue that the second line is a continuation of the first. The example you posted does look strange, but I'm not sure the example as it stands is realistic code (except insofar as you might have code in this state for a few seconds before you continued typing).

If you can formulate a few code examples with what you feel would be "correct" indentation around this area (e.g. two-line statements), we can discuss whether the formatter handles them in a reasonable way.

**Comment by jamshark70** [comment]
The end goal would be:

```
p.collect { |path|
    ... something with path...
}
```

... with minimum manual adjustment.

But you're quite right to point out that this *is* the end result, if you just keep typing and hit return.

Some quibbles though:

Because the `}` isn't tabbed after an `arg` list, then it's easy to end up with this:

```
f = { arg abc;
abc+1;
};
```

And if there's more than one line in the function:

```
f = { |abc|
    abc = abc * 2;
abc + 1;  // this line gets pushed back when "return" un-indents the `}`
};
```

**Comment by scztt** [comment]
What sclang-format gives me now:

```
// before
f = { arg abc;
abc+1;
};

// after
f = { arg abc;
    abc+1;
};
```

```
// before
f = { |abc|
    abc = abc * 2;
abc + 1;  // this line gets pushed back when "return" un-indents the `}`
};

// after 
f = { |abc|
    abc = abc * 2;
    abc + 1;  // this line gets pushed back when "return" un-indents the `}`
};
```

I see what you mean re your last example - this case is resolved for me if I turn on "format on type" - without this formatting is not triggered when you hit return.

Do you see any other languages that get this right without "format on type"? I tried a more or less identical example in Typescript (VSCode is written in typescript, so I'd expect it's behavior here to be as good as it gets), and it does the same thing as sclang does now.

**Comment by jamshark70** [comment]
> this case is resolved for me if I turn on "format on type"

That's good to know, thanks for the tip.

I was unable to build sclang-format, though, based on given information. I'll follow up in that repository. At present, "format on type" isn't working in my environment.

> Do you see any other languages that get this right without "format on type"?

That's a valid point -- it's not realistic to expect that.

FWIW: I am not using any other languages, and I don't know the feature set of vscodium... but I'm at least experienced enough to log (hopefully) useful bug reports, and show where "normal" SC users will get tripped up. Appreciate your patience with that -- I think in the long run it will make vscode-sc more approachable for a broader base of SC users.

**Comment by scztt** [comment]
Thanks for the legwork and detailed reports, these subtleties are very important.

You might check out the language config: https://github.com/scztt/vscode-supercollider/blob/develop/language-configuration.json 
(https://code.visualstudio.com/api/language-extensions/language-configuration-guide) to see if there are any obvious mistakes or things that could be added to improve the basic language support. I think I have most things covered, but I'm sure there are improvements to be made.
