### ISSUE TITLE
On MacOS, parallel use with SC-IDE is somewhat limited.

### ISSUE THREAD

**Issue by prko** [scztt/vscode-supercollider#40]
Please see:
https://github.com/supercollider/supercollider/issues/6204

See also the following post and subsequent posts in the same thread:
https://scsynth.org/t/can-sclang-detect-the-ide-it-is-currently-using/8873/5?u=prko

I think this is not a problem with your `vscode-supercollider', but with SuperCollider on MacOS. However, I think it should be mentioned here too, as I found this while using `vscode-supercollider'. 

Sorry for the cross-posting, and thanks again for your great software!

**Comment by scztt** [comment]
I believe this is resolved by https://github.com/scztt/LanguageServer.quark/commit/74747ab4909fec1452b7944fddc4482cfe933e3b.
On my Mac system, I can now launch the old ScIDE with no problems in parallel to the VSCode plugin.
