### ISSUE TITLE
sclang-format inside vscode-supercollider

### ISSUE THREAD

**Issue by prko** [scztt/vscode-supercollider#41]
Hello,

I am sorry to request too many things. This would be my last request.

Could your `sclang-format` be integrated with `vscode-supercollider`?
In the context menu of vscode, there are three kinds of `Format` items.

![Screenshot 2024-01-31 at 15 32 02](https://github.com/scztt/vscode-supercollider/assets/416281/a5a916e5-d4ab-4bf3-b93d-5f7881499dda)

I tried to get back the formatted code by utilising the following SC code, but could not do it:
```
"cat ~/Downloads/test.scd | sclang-format".unixCmdGetStdOut
```

**Comment by scztt** [comment]
This is working now.
