### ISSUE TITLE
InitializeProvider and suggestedServerPort

### ISSUE THREAD

**Issue by spluta** [scztt/vscode-supercollider#54]
The following code:

```
Server(("oscOS_nrt"++1000.rand).asSymbol,
    options: Server.local.options
    .numOutputBusChannels_(2)
    .numInputBusChannels_(2)
);
```

throws the following error:

```
^^ ERROR: Message 'suggestedDefaultPort' not understood.
RECEIVER: InitializeProvider
```

I added the following to InitializeProvider.sc to get this to work:

```
*suggestedDefaultPort {^suggestedServerPort}
```

But I imagine this is a deeper issue I don't quite understand.

Sam

**Comment by scztt** [comment]
Fixed by https://github.com/scztt/LanguageServer.quark/commit/548f6e6fb4a35bdb7ce185f206fb26b4e3d7c9fb
