### ISSUE TITLE
ServerTree.add is not updating global variables

### ISSUE THREAD

**Issue by jenshaase** [scztt/vscode-supercollider#59]
Hello,

I found a bug when using global variables and `ServerTree.add`.

This is the code I have:

```
(
    ServerTree.removeAll();
    ServerTree.add({
        ~fxGroup = Group.new;
    })
)
    
~fxGroup
```

Then I will do the following:

* I evaluate the first region
* I press `Cmd + .` to create a new group. The group is existing on the server.
* I evaluate the line `~fxGroup`
* I would expect that that `~fxGroup` evaluates to the group number, but it is evaluating to `nil`.

If I do the same in ScIDE I get the expected value and pressing `Cmd + .` multiple times will update the global variable `~fxGroup`.

Some additional note:
* If I evaluate `CmdPeriod.run()` instead of pressing `Cmd + .` everything is working as expected.

**Comment by scztt** [comment]
Hi Jens - this case should be improved in the newest LanguageServer builds. I reworked the code evaluation model quite a lot - I don't observe any Environment issues like this any more. However: the way sclang swaps environments per-thread feels somewhat fragile to me, so please report any other observations of bad behavior.
